language: php

notifications:
  email:
    on_success: never

php:
  - 7.2
  - 7.3
  - nightly

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: dependencies=lowest

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

before_script:
  - pip install --user awscli
  - pip install --user aws-sam-cli
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse

env:
  matrix:
    - secure: GgEjHdzQn6FcAsasGodBrFlQ7FKu9zy2GghlEzDcsLDp0JMNzkJtpX0pJoiWyicdCrUXGHvJx+c7xwCv1Cm3D+lmi25oreSPT9XBxa1N6d//UFwiDoYATWDiuTUUv9m9jSztHQjCqdfZEmF8gsB9CfcmkJqOdn3g4W+RbWAgr08k2Ow2MuNefGkEp9xSqJZ4/jnAbZNsk4BpLNAWCkoUgz/kf1eeRB36bHZDUdBJcdY2pNmNhB8DTBiO2zAuhcI8xeMKnN60OHCMnfnver4l3P5ayfrF9bdNcL4crPO5eqmVojXiS9kBP1XlxRHiSEyqo8cZXFlWBp5VcqBcDumPiPYyuZ/VS4lxGezSQnJZqRJNvHBI/MRZhdzMxRMH+J2YyCNmju6YTrT6TBFdRQgm+sF+SBO1s9nF+KgddbFsyFcHw6oDEfVmcV2XEYT5xUNF1JZRo/J6lIefAcECfWf+WuAyLe+lakT7X76+Vm97CGLQfJ4WdGP586LbTCEa24vUnqsEOA9aKltRCFSE7fL8TdBBKDEc7uxhdweewGlE851gvgqPCGOih1NwQ4PECeiQjiibA+OEajUvGZOSiIoZV8JmvkcCeMeo1Ez1oZsCDTnkDRgp9X82Ne+9s6uaNMMW/aFWG6NZV8bvzDm3S2ux0qlw6qUjzgJYdyudbmV3KMQ=
    - secure: WAOA201xFoB9JpNpon8ZN3mwBGIHAPzR3Zx3pzxhUUhk+onMqSwaUPGzdsRutP191ud/sv69fa+l7+hbpiZ6ZjQUjxIGTEbe22SY9WESCco8ZxjVbPa3ypmp7eE4Ee32GS2adKfdgabID/3yr67R9ChP/vOyBsz0taObPBENwMgzNPmdmQpb+7h8k7L7VUYzH8s2Ge9V7oS3AkrmsjBigGTBxpRI/xEXy29h/kJStaM3HHyLLASy2b+bx5gVv5PBx8jhmo0oKNVB85ziMQvXaaBj2F6hoL6R7UuLzvUgtTot4Xw+0e9HsfdFiaH6tFmJOaStT8xOaehfFA4xRBd14d78gYdlitFGQzYbD1Hvzs/w2dGDf9gXGuGXd4nyXaK6SpqTNLbX9FJID/XGLO7BCCJx/T9UQZ1a4FvtPjDXLJzKvYJY0isV77zRbqwN/8hizMFiP0TBdRmDjo3u+UtV0nmmEnzTOR17ErVNDDsfjGRf3F9sqb3ciYsFHRFYCuEh9M0Bd6Ks7ub881TSztAbfEt6et0nloj72MSjpohilCCk98uTGOWSBkRY6cMKLJsIIbKc5Xvf+jzNwBaSCvfok3XNIWz/ZNMqag6FAQd/P3GpCI5PgTL09bkqnap55/wwbZ2c8fpCKYFjggCvtkeAdKb8TFwaAhDaVNtMNTzY3g8=
