language: php

notifications:
  email:
    on_success: never

php:
  - 7.2
  - 7.3
  - nightly

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env: dependencies=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;
  - pip install awscli
  - pip install aws-sam-cli

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyse
