service: test

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - '*'
    - '**'
  include:
    - handler.js
    - lambda.php
    - 'bin/**'
    - 'src/**'
    - 'vendor/**'

functions:
  # By default we create one "main" function
  main:
    handler: handler.handle
    # Use the minimum amount of memory (Mb) by default to optimize costs
    # Increase if necessary
    memorySize: 128
    timeout: 20
    # The function will match all HTTP URLs
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'

plugins:
  - phplambda

custom:
  phpbuild:
    - 'composer install --no-dev --optimize-autoloader'
