service: app

provider:
    name: aws
    runtime: provided

functions:
    function:
        handler: index.php
        description: ''
        layers:
            - 'arn:aws:lambda:us-east-1:209497400698:layer:php-73:6'
