blank_issues_enabled: false
contact_links:
    - name: Community support
      url: https://github.com/brefphp/bref/discussions?discussions_q=category%3ASupport
      about: Please ask and answer questions in GitHub Discussions.
    - name: Professional support
      url: https://bref.sh/#enterprise
      about: Get in touch with Null, the company behind Bref.
    - name: Feature idea
      url: https://github.com/brefphp/bref/discussions?discussions_q=category%3AIdeas
      about: Discuss new features and other ideas in GitHub Discussions.
