AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'my-function'
            Description: ''
            CodeUri: .
            Handler: app/console # Replace by `artisan` if you are using Laravel
            Timeout: 30 # in seconds
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:us-east-2:416566615250:layer:php-72:9' # PHP
                - 'arn:aws:lambda:us-east-2:416566615250:layer:console:1' # The "console" layer
