version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
      php: 7.3

  build:
    commands:
      # Install Composer
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"

      # Necessary for publish.php to use Symfony Processor
      - php composer.phar install

      # Copy AWS config to be able to automatically assume role into the layer account
      - mkdir ~/.aws && copy ./runtime/pipeline/config ~/.aws/config

      - make runtimes

