version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      docker: 19
      php: 7.3

  build:
    commands:
      # Install GH CLI
      - curl https://cli.github.com/packages/rpm/gh-cli.repo --output /etc/yum.repos.d/gh-cli.repo
      - yum install -y gh

      # Configure GitHub User
      - git config --global user.email "deleugyn+bref@gmail.com"
      - git config --global user.name "[Bot] Marco Deleu"

      - git checkout master
      - git status
      - git checkout -b bref/layers
      - echo "testing" > testing.json

      - git add testing.json
      - git commit -m "layer.json update"

      - git remote add github https://brefphp-bot:${GITHUB_TOKEN}@github.com/brefphp-bot/bref.git
      - git push --set-upstream github bref/layers --force

      - gh pr create --title "New PHP Layers" --reviewer "mnapoli" --body "New layers have finished building" --base brefphp:master --head "brefphp-bot:bref/layers"

      # Login to Docker Hub to avoid rate limit
#      - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD

      # Install Composer
#      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
#      - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
#      - php composer-setup.php
#      - php -r "unlink('composer-setup.php');"

      # Necessary for publish.php to use Symfony Processor
#      - php composer.phar install

      # Copy AWS config to be able to automatically assume role into the layer account
#      - mkdir ~/.aws && cp ./runtime/pipeline/config ~/.aws/config

#      - make runtimes

