name: Tests

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'
    schedule:
        -   cron: '0 0 * * *'

jobs:

    php-tests:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        env:
            COMPOSER_NO_INTERACTION: 1
        strategy:
            matrix:
                php: [ '8.0', '7.4', '7.3', '7.2' ]
                dependency-version: [ prefer-stable ]
                include:
                    -   php: '7.2'
                        dependency-version: prefer-lowest
        name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none
                    tools: composer
            # See https://github.com/shivammathur/setup-php/issues/280
            -   name: Install php-fpm
                env:
                    version: ${{ matrix.php }}
                run: 'sudo apt-get install -y php$version-fpm'
            -   name: Install dependencies
                run: 'composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress'
            -   name: Execute Unit Tests
                run: 'vendor/bin/phpunit --testsuite small'

    phpstan:
        runs-on: ubuntu-latest
        name: PHPStan
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer
            -   name: Install dependencies
                run: 'composer install --prefer-dist --no-progress'
            -   name: PHPStan
                run: 'vendor/bin/phpstan analyse'

    phpcs:
        runs-on: ubuntu-latest
        name: PHP CodeSniffer
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer
            -   name: Install dependencies
                run: 'composer install --prefer-dist --no-progress'
            -   name: PHPStan
                run: 'vendor/bin/phpcs'
